name: ADR Checker

on:
  workflow_dispatch

jobs:
  run-ADR-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Python Script
        run: |
          python -m pip install requests
          python -m pip install behave
          behave
      
