name: ADR Checker

on:
  workflow_dispatch

jobs:
  run-ADR-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Run Python Script
        if: always()
        run: |
          python -m pip install requests
          python -m pip install behave
          python -m pip install gemfileparser
          behave

      - name: Logging Results
        if: failure()
        run: | 
          echo "Generate a Report Here"
